image:
  tag: 3.5.2
listeners:
  client:
    protocol: SASL_PLAINTEXT
  interbroker:
    protocol: SASL_PLAINTEXT
  external:
    protocol: SASL_PLAINTEXT
persistence:
  enabled: false
broker:
  replicaCount: 5