apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-script
data:
  fetch_weather.sh: |
    #!/bin/bash
    CITIES=("Minsk" "Moscow" "Saint Petersburg" "Sochi" "Hurghada" "Istanbul")
    DATA_DIR="/data"
    TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
    API_KEY="10057f8b0b996e0652dc4ae3e5af7a81"
    for city in "${CITIES[@]}"; do
      # Получаем данные о погоде (используем mock для примера)
      #TEMPERATURE=$((RANDOM % 30 - 5))  # Замените на реальный API запрос
      #WIND_SPEED=$((RANDOM % 20))       # Замените на реальный API запрос
      TEMPERATURE=$(curl -s "http://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${API_KEY}" | jq '.main.temp')
      WIND_SPEED=$(curl -s "http://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${API_KEY}" | jq '.wind.speed')
      # Формируем имя файла
      FILENAME="${DATA_DIR}/${city}_${TIMESTAMP}.txt"
      
      # Записываем данные в файл
      echo "City: $city" > $FILENAME
      echo "Time: $(date)" >> $FILENAME
      echo "Temperature: ${TEMPERATURE}°C" >> $FILENAME
      echo "Wind Speed: ${WIND_SPEED} m/s" >> $FILENAME
    done

## http://api.openweathermap.org/data/2.5/weather?q=Minsk&units=metric&appid=10057f8b0b996e0652dc4ae3e5af7a81
## https://api.open-meteo.com/v1/forecast?latitude=53.9&longitude=27.5667&hourly=temperature_2m,wind_speed_10m&timezone=Europe%2FMoscow&forecast_days=1