apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-collector
  template:
    metadata:
      labels:
        app: weather-collector
    spec:
      containers:
      - name: weather-collector
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - apk add --no-cache curl bash;
            while true; do
              /script/fetch_weather.sh;
              sleep 1200; # 20 минут = 1200 секунд
            done
        volumeMounts:
        - name: weather-script
          mountPath: /script
        - name: weather-data
          mountPath: /data
      volumes:
      - name: weather-script
        configMap:
          name: weather-script
          defaultMode: 0777
      - name: weather-data
        persistentVolumeClaim:
          claimName: weather-data-pvc
      restartPolicy: Always