apiVersion: v1
kind: Pod
metadata:
  name: file-generator
  namespace: kube-system
spec:
  containers:
    - name: file-generator
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            filename=$(date +'%Y-%m-%d_%H-%M-%S').txt
            random_text=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
            echo "$random_text" > /data/$filename
            echo "Created file $filename with content: $random_text"
            sleep 8
          done
      volumeMounts:
        - name: data-storage
          mountPath: /data
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        #requests:
        #  memory: "64Mi"
        #  cpu: "250m"
  volumes:
    - name: data-storage
      persistentVolumeClaim:
        claimName: my-sci3
        readOnly: false