apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-sci3
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  #volumeName: homework-s3
  storageClassName: "csi-s3-2"