apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: "YCAJEKjQUAbsLh0Ouvp-hIv2q"
  secretAccessKey: "YCNXOy0QdAm_lLxzYH4LFRyLxb6Wiie6tUE3iIkP"
  endpoint: https://storage.yandexcloud.net