# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
k8s2-cp1 ansible_host=158.160.153.173
k8s2-cp2 ansible_host=158.160.179.74
k8s2-w1 ansible_host=158.160.172.234
k8s2-w2 ansible_host=158.160.168.185
k8s2-w3 ansible_host=130.193.58.7
# node1 ansible_host=95.54.0.12  # ip=10.3.0.1 etcd_member_name=etcd1

# ## configure a bastion host if your nodes are not directly reachable
# [bastion]
# bastion ansible_host=x.x.x.x ansible_user=some_user

[kube_control_plane]
k8s2-cp1
k8s2-cp2

[etcd]
k8s2-cp1
k8s2-cp2
k8s2-w1

[kube_node]
k8s2-w1
k8s2-w2
k8s2-w3
