apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: new-standard
provisioner: disk-csi-driver.mks.ycloud.io
reclaimPolicy: Retain # default: Delete
volumeBindingMode: Immediate