image:
  tag: latest
listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
persistence:
  enabled: false
broker:
  replicaCount: 1