prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: monitoring.otus
    path: /
    pathType: Prefix
    ## Второй вариант (extraRules) как можно ingress настроить
    #extraRules:
    #- host: monitoring.otus
    #  http:
    #    paths:  # Замените http.path на http.paths
    #    - path: /
    #      pathType: Prefix
    #      backend:
    #        service:
    #          name: prom-svc
    #          port:
    #            name: http
    #resources:
    #  requests:
    #    cpu: 100m
#       memory: 64Mi
    #  limits:
    #    cpu: 200m
#       memory: 1024Mi
#operator: 
resourcesPreset: "none" ## Мтапндартное resourcesPreset: "nano"
resources:
  requests:
    cpu: 100m
#       memory: 64Mi
  limits:
    cpu: 200m
#       memory: 1024Mi