prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: monitoring.otus
    path: /
    pathType: Prefix
    extraRules:
    - host: monitoring.otus
      http:
        paths:  # Замените http.path на http.paths
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prom-svc
              port:
                name: http
    #hosts:
    #  - host: monitoring.otus
    #    paths:
    #      - path: /
    #        pathType: Prefix
    #tls:
    #  - secretName: prometheus-tls
    #    hosts:
    #      - prometheus.example.com
#operator: 
#  resources:
#     requests:
#       cpu: 64Mi
#       memory: 64Mi
#     limits:
#       cpu: 1
#       memory: 1024Mi