apiVersion: v1
kind: ServiceAccount
metadata:
  #annotations:
  #  kubernetes.io/enforce-mountable-secrets: "true"
  name: monitoring
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  #namespace: homework
  name: metrics-reader
rules:
#- apiGroups: [""]
#  resources: ["nodes/metrics"]
#  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-access
  namespace: homework
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: homework
roleRef:
  kind: ClusterRole
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
