apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: new-standard
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain # default: Delete
volumeBindingMode: Immediate