#repositories:
#  - name: argo
#    url: https://argoproj.github.io/argo-helm

releases:
  - name: vault
    namespace: vault
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/vault
    version: 1.19.1 ## версии тут https://artifacthub.io/packages/helm/bitnami/vault
    values:
      - vault-values.yaml

  - name: consul
    namespace: consul
    createNamespace: true
    chart: oci://registry-1.docker.io/bitnamicharts/consul
    version: 1.20.5 ## версии тут https://artifacthub.io/packages/helm/bitnami/consul
    values:
      - consul-values.yaml