apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
   matchLabels:
     app: web-server-deployment
  template:
   metadata:
     labels:
       app: web-server-deployment
  containers:
    initContainers:
    - name: init-config
      image: busybox
      command: ['sh', '-c', 'echo "<h1>Hello my Friend</h1>" > /init/index.html']
      volumeMounts:
      - name: nginx-config
        mountPath: /init
    - name: nginx
      image: nginx:alpine
      ports:
      - containerPort: 8000
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh","-c","echo 'server { listen 8000; location / { root /homework; index index.html; } }' > /etc/nginx/conf.d/default.conf"]
        preStop:
          exec:
            command: ["/bin/sh","-c","rm /homework/index.html"]
        readinessProbe:
            exec:
              command: test -f /homework/index.html
      volumeMounts:
      - name: nginx-config
        mountPath: /homework
    volumes:
      - name: nginx-config
        emptyDir: {}
    strategy:
     type: RollingUpdate
     rollingUpdate:
       maxUnavailable: 1