apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #nodeName: minikube
      initContainers:
        - name: init-config
          image: busybox
          command: ['sh', '-c', 'echo "<h1>Hello my Friend</h1>" > /init/index.html && echo "http { server { listen 8000; location / { root /homework; index index.html; } } }" > /etc/nginx/conf.d/default.conf']
          volumeMounts:
            - name: nginx-config
              mountPath: /init
      containers:
        - name: nginx
          image: nginx:1.27.1
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-config
              mountPath: /homework
          lifecycle:
            #postStart:
              #exec:
                #command: ["/bin/sh","-c","echo 'http { server { listen 8000; location / { root /homework; index index.html; } } }' > /etc/nginx/conf.d/default.conf && nginx -t && nginx -g 'daemon off;'"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm /homework/index.html"]
          readinessProbe:
            exec:
              command: ["sh", "-c", "sleep 5 && test -f /homework/index.html"]
      volumes:
        - name: nginx-config
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
