apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
  namespace: homework
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Документ</title>
        <style>
            body {
                color: red;
            }
        </style>
    </head>
    <body>
        абракадабра
    </body>
    </html>
