apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  initContainers:
  - name: init-config
    image: busybox
    command: ['sh', '-c', 'echo "server { listen 8000; location / { root /usr/share/nginx/html; index index.html; } }" > /etc/nginx/conf.d/default.conf']
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-config
    emptyDir: {}