apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  initContainers:
  - name: init-config
    image: busybox
    command: ['sh', '-c', 'echo "server { listen 8000; location / { root /homework; index index.html; } }" > /etc/nginx/conf.d/default.conf && echo "<h1>Hello my Friend</h1>" > /usr/share/nginx/html/index.html']
    volumeMounts:
    - name: nginx-config
      mountPath: /init
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 8000
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh","-c","rm /homework/index.html"]
    volumeMounts:
    - name: nginx-config
      mountPath: /homework
  volumes:
  - name: nginx-config
    emptyDir: {}